import React from 'react';

interface PageProps {
  onNavigate: (path: string) => void;
}

export default function TermsPage({ onNavigate }: PageProps) {
  return (
    <div className="min-h-screen w-full bg-[#040806] text-gray-200 flex flex-col justify-between p-6 md:p-12 font-['Inter',sans-serif] select-text relative">

      <header className="w-full max-w-4xl mx-auto flex items-center justify-between z-20 pb-8 border-b border-gray-800/80 mb-10">
        <button onClick={() => onNavigate('/')} className="flex items-center gap-3 cursor-pointer group">
          <span className="text-white text-xl font-medium tracking-wider group-hover:text-blue-400 transition-colors">
            AEGIS
          </span>
        </button>
        <nav className="flex items-center gap-6 text-xs text-gray-400 font-normal tracking-wide">
          <button onClick={() => onNavigate('/terms')} className="text-white font-medium cursor-pointer border-b border-gray-400 pb-0.5">Terms of Service</button>
          <button onClick={() => onNavigate('/privacy')} className="hover:text-white transition-colors cursor-pointer">Privacy Policy</button>
          <button onClick={() => onNavigate('/docs')} className="hover:text-white transition-colors cursor-pointer">Documentation</button>
          <button onClick={() => onNavigate('/contact')} className="hover:text-white transition-colors cursor-pointer">Contact Us</button>
          <button onClick={() => onNavigate('/')} className="bg-gray-800 hover:bg-gray-700 text-white px-3 py-1.5 rounded text-xs transition-colors cursor-pointer ml-2">
            Back to Platform
          </button>
        </nav>
      </header>


      <main className="flex-1 w-full max-w-4xl mx-auto space-y-6 text-sm text-gray-300 font-normal leading-relaxed">

        <h1 className="text-3xl md:text-4xl font-semibold text-white tracking-tight mb-6">
          Terms of Service
        </h1>

        <p className="text-base text-gray-200 leading-relaxed font-normal">
          These Terms of Service govern your access to and use of the Aegis platform, Sentinel Gateway, Sovereign Node software, and CLI tools. By using Aegis, satellite operators and organizations agree to comply with these terms.
        </p>

        <div className="space-y-4 pt-2">
          <h2 className="text-xl font-semibold text-white tracking-tight">1. Operator Node Deployment and Data Control</h2>
          <p className="text-sm text-gray-300 leading-relaxed">
            Satellite operators deploying self hosted Sovereign Nodes retain full operational control over their private telemetry parameters, thruster performance profiles, and financial downtime data. Aegis does not claim ownership over local operator telemetry.
          </p>

          <h2 className="text-xl font-semibold text-white tracking-tight">2. Multi Agent Arbitration Rulings</h2>
          <p className="text-sm text-gray-300 leading-relaxed">
            Arbitration verdicts generated by the Supreme Court Enclave use game theoretic Nash Bargaining models and 3D orbital dynamics calculations to assign right of way maneuver duty. Operators acknowledge that arbitration outputs provide automated collision avoidance guidance subject to physical orbital constraints.
          </p>

          <h2 className="text-xl font-semibold text-white tracking-tight">3. Security and Cryptographic Verification</h2>
          <p className="text-sm text-gray-300 leading-relaxed">
            Aegis utilizes hardware encrypted Trusted Execution Environments and cryptographic key management services to generate verifiable attestation proofs. Modifying or tampering with cryptographic attestation tokens is strictly prohibited.
          </p>

          <h2 className="text-xl font-semibold text-white tracking-tight">4. Limitation of Liability</h2>
          <p className="text-sm text-gray-300 leading-relaxed">
            Aegis provides space domain intelligence and risk calculations on an as is basis. Satellite operating entities retain final command responsibility for issuing thruster firing sequences to their respective spacecraft.
          </p>
        </div>

      </main>


      <footer className="w-full max-w-4xl mx-auto flex items-center justify-between text-xs text-gray-500 pt-8 border-t border-gray-800/80 mt-12">
        <span>© 2026 Aegis</span>
        <span>Terms of Service</span>
      </footer>
    </div>
  );
}
